# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Message:
  fields:
    default: user, content, tag_list
    form: user, content, tag_list
  order_by: user
  relationships: 
  filters: 
  search: 
  application: Unofficial Salesforce Knowledge Base


