# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Message:
  fields:
    default: user, content
    form: user, content
  order_by: user
  relationships: 
  filters: 
  search: 
  application: rails_cinch


